name: 'Walk Files'
description: 'Walk through files in the given repo, maybe'
#inputs:
#  who-to-greet:  # id of input
#    description: 'Who to greet'
#    required: true
#    default: 'World'
outputs:
  count: # counts of the target file extension
    description: 'The number of files of a type'
runs:
  using: 'node16'
  main: 'index.js'
