name: 'Walk Files'
description: 'Walk through files in the given repo, maybe'
inputs:
  file-type-to-seek:  # id of input
    description: 'File type to seek'
    required: true
    default: 'md'
  dir-to-walk:
    description: 'Which directory to walk through'
    required: true
    default: ${{ github.workspace }}
outputs:
  count: # counts of the target file extension
    description: 'The number of files of a type'
  results: # files found
    description: 'The list of files found'
runs:
  using: 'node16'
  main: 'index.js'
